
FROM osrf/ros:foxy-desktop

SHELL ["/bin/bash", "-c"]

RUN apt update
RUN apt install -y \
  ros-foxy-gazebo-ros-pkgs \
  ros-foxy-gazebo-plugins \
  ros-foxy-xacro 
RUN apt -y install ros-foxy-ros2-control
RUN apt -y install ros-foxy-ros2-controllers
RUN apt -y install ros-foxy-gazebo-ros2-control

RUN apt install ros-foxy-ros-core ros-foxy-geometry2


WORKDIR /app

COPY ./ros_entrypoint.sh ./ros_entrypoint.sh
RUN chmod +x ./ros_entrypoint.sh

# Use caminho absoluto para o entrypoint
ENTRYPOINT ["/app/ros_entrypoint.sh"]
CMD ["bash"]

