controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    velocity_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - Dir_E_T  
      - Dir_E_F  
      - Dir_D_F  
      - Dir_D_T  
      - Fix_2  
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    open_loop_control: true
    allow_nonzero_velocity_at_trajectory_end: false

velocity_controller:
  ros__parameters:
    joints:
      - fix_1
      - Wheel_E_F  
      - Wheel_D_T  
      - Wheel_D_F  
      - Wheel_E_T  
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    open_loop_control: true
    allow_nonzero_velocity_at_trajectory_end: true
