controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

      left_wheel_names: ["left_wheel_joint"]
      right_wheel_names: ["right_wheel_joint"]

      wheel_radius: 0.1
      wheel_separation: 0.6

      base_frame_id: base_link
      publish_rate: 50
      cmd_vel_timeout: 0.5
      use_stamped_vel: false
